version: '3'
volumes:
  pgdata:
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: vehicle
    ports:
    - 5432:5432
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:Z
  discovery:
    image: quay.io/hyperfoil/vehicle-market-vehicle-discovery
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: [ postgres ]
    ports:
    - 8081:8081
  listing:
    image: quay.io/hyperfoil/vehicle-market-listing-service
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: [ postgres ]
    ports:
    - 8082:8082
  user:
    image: quay.io/hyperfoil/vehicle-market-user-service
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: [ postgres ]
    ports:
    - 8083:8083
  frontend:
    image: quay.io/hyperfoil/vehicle-market-frontend
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - 8080:8080
    depends_on:
    - user
    - listing
    - discovery
    entrypoint: /deployments/entrypoint.sh
